"""
Levititas v3.3 — Brand Name Generator
static/js/brand.py (server-side, called by server.py)

Generates randomized brand name variants for output headers.
The original brand seed never appears as plaintext anywhere.
Generated via character substitution + glyph mixing.
"""

import random
import base64
import hashlib
import time

# Brand seed stored as base64 — never plaintext in source
_BRAND_SEED = base64.b64decode("TGV2aXRpdGFz").decode()  # Levititas

# Substitution tables (per glyph set)
_SUBS = [
    # Set A — leet-style
    {"e": "3", "i": "1", "a": "4", "o": "0", "t": "7", "s": "5"},
    # Set B — symbol injection
    {"e": "€", "i": "!", "a": "@", "o": "0", "t": "+", "s": "$"},
    # Set C — mixed case + glyph
    {"e": "E", "i": "I", "a": "A", "o": "O", "t": "T", "s": "S"},
    # Set D — unicode lookalikes
    {"e": "ε", "i": "ι", "a": "α", "o": "ο", "t": "τ", "s": "ς"},
    # Set E — partial replacement
    {"e": "e", "i": "i", "a": "a", "o": "o", "t": "†", "s": "ƨ"},
]

# Drop patterns (remove 1-2 characters randomly)
_DROP_PATTERNS = [
    [2, 5],   # Le_ita_
    [3],      # Lev_itas
    [4, 6],   # Levi_it_s
    [1],      # _evititas
    [5, 7],   # Levit_ta_
]

def generate_brand(build_seed: int = None) -> str:
    """
    Generate a randomized brand name for the output header.
    Every call with a different seed produces a different result.
    The output looks like a variant of the brand but is never identical.
    """
    if build_seed is None:
        build_seed = int(time.time() * 1000) ^ int(time.time())

    rng = random.Random(build_seed)
    brand = _BRAND_SEED  # "Levititas"

    # Step 1: Apply substitution table
    sub_table = rng.choice(_SUBS)
    result = ""
    for ch in brand:
        lower = ch.lower()
        if lower in sub_table and rng.random() > 0.35:
            sub = sub_table[lower]
            result += sub.upper() if ch.isupper() and sub.isalpha() else sub
        else:
            result += ch

    # Step 2: Drop pattern (shorten)
    drop = rng.choice(_DROP_PATTERNS)
    chars = list(result)
    for idx in sorted(drop, reverse=True):
        if idx < len(chars):
            chars.pop(idx)
    result = "".join(chars)

    # Step 3: Case mutation
    final = ""
    for ch in result:
        if ch.isalpha() and rng.random() > 0.6:
            final += ch.swapcase()
        else:
            final += ch

    # Step 4: Ensure minimum length
    if len(final) < 4:
        final = result[:4]

    return final


def generate_header_comment(build_seed: int = None) -> str:
    """
    Generate the full output file header comment.
    """
    brand = generate_brand(build_seed)
    ts = time.strftime("%Y-%m-%d")
    return f"-- This file was generated by {brand} | {ts}"


def get_brand_variants(n: int = 8) -> list:
    """Return n different brand variants for display."""
    base = int(time.time())
    return [generate_brand(base + i * 7919) for i in range(n)]


if __name__ == "__main__":
    print("Brand variants:")
    for v in get_brand_variants(10):
        print(f"  {v}")
    print("\nHeader:")
    print(generate_header_comment())
