"""
Leviathan Obfuscator v3.3 — Brand Header Generator
brand.py  (project root — NOT in static/)

Generates opaque, randomized build tokens for the output file header.

Token format spec:
  1. Pick a random Leviathan name variant  e.g. LvtTus, Lvthn, L3vt
  2. Combine with a random salt
  3. Encode with a custom non-standard Base64 alphabet
  4. Strip '=' padding and any characters resembling standard Base64
  5. Result looks like a random alphanumeric token: xA7QmLp2NfK
  6. Every call produces a different token

The raw alias NEVER appears in the output.
"""

import random
import base64
import struct

# ── Name variant pool ──────────────────────────────────────────────────────────
# Short, pronounceable, Leviathan-themed aliases.
# These are encoded, not emitted directly.
_VARIANTS = [
    "LvtTus", "Lvthn",  "L3vtn",  "LVT-X",  "LvthN",
    "Lev3tus","L3vithn","Lvtn",    "LvtX",   "L3vt",
    "Leviath","LvX3",   "LVX",     "L3VX",   "Lvthx",
    "LvTN",   "L3Vtn",  "LVTN",    "Lv7n",   "L3v7",
]

# ── Custom Base64 alphabet ─────────────────────────────────────────────────────
# Shuffled so the output looks nothing like standard Base64.
# Standard: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/
# Custom:   alphabetically scrambled with digits interleaved
_STD_B64  = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
_CUST_B64 = "xK9mQpN3wRvL7jYdZaGb2ThXs8cFeU4ioPkntgu6E1WIlrC5MJyfBzDVHSO0qA-_"
# Sanity: must be 64 chars, all unique
assert len(_CUST_B64) == 64 and len(set(_CUST_B64)) == 64, "Custom alphabet invalid"

# Build translation table (std → custom char-by-char)
_TRANS = str.maketrans(_STD_B64, _CUST_B64)

def _encode(data: bytes) -> str:
    """Encode bytes with custom alphabet, strip padding."""
    b64 = base64.b64encode(data).decode("ascii")
    return b64.translate(_TRANS).rstrip("=").rstrip(_CUST_B64[-1])


def generate_brand(seed: int | None = None) -> str:
    """
    Generate a single opaque build token.

    Returns a 10–14 character token like xA7QmLp2NfK.
    The Leviathan variant is encoded inside — never visible directly.
    """
    rng = random.Random(seed) if seed is not None else random.Random()

    # 1. Pick variant
    variant = rng.choice(_VARIANTS)

    # 2. Build payload: variant bytes + 3 random salt bytes
    salt    = bytes(rng.randint(0, 255) for _ in range(3))
    payload = variant.encode("ascii") + salt

    # 3. Encode with custom alphabet
    token = _encode(payload)

    # 4. Trim to target length (10–14 chars)
    token = token[:14]
    if len(token) < 10:
        # Pad with encoded random bytes until long enough
        extra = _encode(bytes(rng.randint(0, 255) for _ in range(4)))
        token = (token + extra)[:14]

    return token


def generate_header_comment(seed: int | None = None) -> str:
    """
    Returns the one-line header comment to prepend to obfuscated output.
    Format: -- This file generated by <TOKEN>
    """
    return f"-- This file generated by {generate_brand(seed)}"


# ── Self-test (run this file directly to verify) ──────────────────────────────
if __name__ == "__main__":
    import time
    print("Brand token examples:")
    for i in range(10):
        seed = int(time.time() * 1000) + i * 7
        token = generate_brand(seed)
        print(f"  seed={seed:<14}  token={token}")

    print("\nDeterminism check:")
    s = 123456
    t1 = generate_brand(s)
    t2 = generate_brand(s)
    print(f"  seed={s} → {t1} == {t2}: {t1 == t2}")

    print("\nUniqueness check (no seed):")
    tokens = {generate_brand() for _ in range(20)}
    print(f"  20 calls → {len(tokens)} unique tokens")

    print("\nHeader format:")
    print(" ", generate_header_comment(999))
