"""
Leviathan Obfuscator v3.3 — Web Server
server.py

Fixes vs previous version:
  F5  brand.py moved to project root (was static/brand.py — public HTTP exposure risk)
  F7  _lua() now prefers lua5.4/lua54 before generic `lua` to prevent version mismatch
  F8  _extract_stage() now recognises Lua module/lexer errors and returns useful codes
      All API errors return structured JSON: {success, code, error, details}
  F2  maxIC uses Python int literal (10_000_000 → 10000000); python supports it but
      the Lua spec.lua is also fixed so this is belt-and-suspenders
"""

from flask import Flask, request, jsonify, render_template
import subprocess, os, uuid, time, json, threading, shutil, random, re

# ── Brand import — from project root, not static/ ─────────────────────────────
import sys
_ROOT = os.path.dirname(os.path.abspath(__file__))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

try:
    from brand import generate_header_comment, generate_brand
except ImportError:
    def generate_brand(seed=None): return "LvtX7"
    def generate_header_comment(seed=None):
        return f"-- This file generated by {generate_brand(seed)}"

app = Flask(__name__, template_folder="templates", static_folder="static")
app.config["MAX_CONTENT_LENGTH"] = 4 * 1024 * 1024

OUTPUT_DIR = os.path.join(_ROOT, "output")
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ── Cleanup ────────────────────────────────────────────────────────────────────
def _cleanup():
    while True:
        time.sleep(600)
        now = time.time()
        for f in os.listdir(OUTPUT_DIR):
            fp = os.path.join(OUTPUT_DIR, f)
            try:
                if now - os.path.getmtime(fp) > 600:
                    os.remove(fp)
            except Exception:
                pass
threading.Thread(target=_cleanup, daemon=True).start()

# ── Lua detection (F7: prefer versioned binary) ────────────────────────────────
def _lua():
    """
    F7: Search order changed — versioned binaries tried first.
    This prevents accidentally picking up Lua 5.3 or 5.1 when `lua` is symlinked
    to an older version, which would cause spec.lua to crash on load.
    """
    for name in ("lua5.4", "lua54", "lua-5.4", "lua"):
        path = shutil.which(name)
        if path:
            # Verify it's actually 5.4+ (belt-and-suspenders)
            try:
                r = subprocess.run([path, "-v"], capture_output=True, text=True, timeout=3)
                ver_str = (r.stdout or r.stderr or "").strip()
                if "Lua 5.4" in ver_str or "Lua 5.5" in ver_str or "LuaJIT" in ver_str:
                    return path
                if name != "lua":
                    # Named specifically — trust it even if version string is odd
                    return path
            except Exception:
                continue
    # Last resort: unversioned `lua` whatever it is
    return shutil.which("lua")

def _lua_version(lua_path):
    if not lua_path: return None
    try:
        r = subprocess.run([lua_path, "-v"], capture_output=True, text=True, timeout=5)
        return (r.stdout or r.stderr or "").strip()
    except Exception:
        return None

_LUA_PATH    = _lua()
_LUA_VERSION = _lua_version(_LUA_PATH)
_CLI_PATH    = os.path.join(_ROOT, "levititas.lua")
_START_TIME  = time.time()

print("[Leviathan v3.3] Starting")
if _LUA_PATH:
    print(f"[Leviathan v3.3] ✓ Lua: {_LUA_VERSION} at {_LUA_PATH}")
else:
    print("[Leviathan v3.3] ✗ Lua not found — install Lua 5.4")

# ── Helper: structured error ────────────────────────────────────────────────────
def _err(code, error, details="", stage="unknown", http=422):
    """
    All API errors return a consistent structure.
    Never returns a blank 422 response.
    """
    return jsonify(
        success = False,
        code    = code,
        error   = error,
        details = details,
        stage   = stage,
    ), http

# ── Helper: extract stage from Lua stderr (F8) ─────────────────────────────────
def _extract_stage(stderr):
    """
    F8: Expanded to recognise common Lua runtime error patterns.
    Previously only matched [X999] error codes and always returned 'unknown'.
    Now maps concrete stderr patterns to actionable stage names.
    """
    if not stderr:
        return "unknown"

    s = stderr.lower()

    # Internal error codes e.g. [P001], [V002], [B003]
    m = re.search(r'\[([A-Z]\d+)\]', stderr)
    if m:
        prefix_map = {'P':'parse','V':'validation','B':'bytecode','R':'runtime','C':'compiler','M':'compat'}
        return prefix_map.get(m.group(1)[0], 'engine')

    # Lua module-not-found (e.g. missing compat.lua)
    if "module" in s and ("not found" in s or "no field" in s):
        return "module_load"

    # Lua lexer errors (spec.lua 10_ etc.)
    if "malformed number" in s:
        return "lua_lexer"

    # Lua syntax errors in user source
    if "syntax error" in s or "unexpected symbol" in s:
        return "parse"

    # Stack overflow / timeout
    if "stack overflow" in s:
        return "runtime"
    if "attempt to" in s:
        return "runtime"

    return "engine"

# ── Helper: extract human error from Lua stderr ───────────────────────────────
def _clean_error(stderr):
    """Extract the most relevant error line from Lua stderr."""
    if not stderr:
        return "Unknown engine error."
    lines = [l.strip() for l in stderr.strip().splitlines() if l.strip()]
    if not lines:
        return "Unknown engine error."
    # Prefer lines with ': ' (Lua error format)
    for line in lines:
        if ': ' in line:
            return line
    return lines[0]

# ── Routes ─────────────────────────────────────────────────────────────────────
@app.route("/")
def index():
    return render_template("index.html")

@app.route("/api/status")
def api_status():
    uptime = int(time.time() - _START_TIME)
    lua_ok = bool(_LUA_PATH)
    return jsonify(
        success     = True,
        version     = "3.3.0",
        lua         = lua_ok,
        lua_version = _LUA_VERSION or "unavailable",
        engine      = "lua-full" if lua_ok else "unavailable",
        ready       = lua_ok,
        uptime      = uptime,
        region      = os.environ.get("REGION", "global"),
        node        = os.environ.get("NODE", "primary"),
        api_status  = "online",
    )

@app.route("/api/compat")
def api_compat():
    return jsonify(success=True, matrix=[
        {"target":"lua54",  "status":"full",    "vm":"full",         "notes":"Recommended target."},
        {"target":"lua53",  "status":"partial", "vm":"full",         "notes":"No <const>/<close>."},
        {"target":"lua52",  "status":"none",    "vm":"none",         "notes":"Not supported."},
        {"target":"lua51",  "status":"none",    "vm":"none",         "notes":"Not supported."},
        {"target":"luajit", "status":"partial", "vm":"source-level", "notes":"No bitwise syntax native."},
        {"target":"luau",   "status":"partial", "vm":"source-level", "notes":"No load() in Roblox."},
    ])

@app.route("/api/brand")
def api_brand():
    seed = request.args.get("seed")
    build_seed = int(seed) if seed and seed.isdigit() else None
    return jsonify(
        success = True,
        brand   = generate_brand(build_seed),
        header  = generate_header_comment(build_seed),
    )

@app.route("/api/obfuscate", methods=["POST"])
def obfuscate():
    # Engine check
    if not _LUA_PATH:
        return _err("NO_LUA_ENGINE",
            "Lua 5.4 runtime is not available on this server.",
            "Install Lua 5.4 or deploy with the provided Dockerfile.",
            stage="engine_check", http=503)

    # Parse request body
    data = request.get_json(force=True, silent=True)
    if not isinstance(data, dict):
        return _err("INVALID_REQUEST", "Request body must be JSON.", http=400)

    source = (data.get("source") or "").strip()
    if not source:
        return _err("EMPTY_SOURCE", "No source code provided.", stage="input", http=400)
    if len(source.encode("utf-8")) > 800_000:
        return _err("SOURCE_TOO_LARGE", "Source exceeds 800 KB limit.", stage="input", http=413)

    opts   = data.get("options", {}) if isinstance(data.get("options"), dict) else {}
    target = str(opts.get("target", "lua54"))
    seed   = opts.get("seed")
    maxIC  = int(opts.get("maxInstructions", 10000000))
    protect= opts.get("protectNames", [])
    if not isinstance(protect, list):
        protect = []

    # Target validation
    valid_targets    = {"lua54", "lua53", "luajit", "luau"}
    unsupported      = {"lua51", "lua52"}
    if target in unsupported:
        return _err("UNSUPPORTED_TARGET",
            f"Target '{target}' is not supported.",
            f"Supported targets: {', '.join(sorted(valid_targets))}",
            stage="compat", http=400)
    if target not in valid_targets:
        return _err("UNKNOWN_TARGET", f"Unknown target '{target}'.",
            stage="compat", http=400)

    # File setup
    uid      = uuid.uuid4().hex
    src_path = os.path.join(OUTPUT_DIR, f"{uid}_in.lua")
    out_path = os.path.join(OUTPUT_DIR, f"{uid}_out.lua")
    build_seed = int(seed) if seed is not None else (int(time.time() * 1000) ^ random.randint(0, 0xFFFF))

    try:
        with open(src_path, "w", encoding="utf-8") as f:
            f.write(source)

        args = [_LUA_PATH, _CLI_PATH, src_path,
                "-o", out_path,
                "--target", target,
                "--max-instr", str(maxIC)]

        if seed is not None:
            args += ["--seed", str(int(seed))]
        for name in protect:
            n = str(name).strip()
            if n:
                args += ["--protect", n]

        t0     = time.time()
        result = subprocess.run(args, capture_output=True, text=True, timeout=30)
        elapsed = round(time.time() - t0, 3)

        if result.returncode != 0:
            stderr = result.stderr or result.stdout or ""
            stage  = _extract_stage(stderr)
            msg    = _clean_error(stderr)
            return _err("ENGINE_ERROR", msg, stderr.strip(), stage=stage, http=422)

        if not os.path.exists(out_path):
            return _err("NO_OUTPUT", "Engine produced no output file.", stage="output", http=500)

        with open(out_path, "r", encoding="utf-8") as f:
            raw = f.read()

        # Replace Levititas engine header with randomized brand token
        brand_header = generate_header_comment(build_seed)
        obfuscated = re.sub(
            r'^-- Levititas v[\d.]+ \|[^\n]*\n',
            brand_header + "\n",
            raw, count=1, flags=re.MULTILINE
        )
        if obfuscated == raw:
            obfuscated = brand_header + "\n" + raw

        return jsonify(
            success = True,
            result  = obfuscated,
            elapsed = elapsed,
            seed    = build_seed,
            brand   = brand_header,
            stats   = _stats(source, obfuscated),
            engine  = "lua-full",
            target  = target,
        )

    except subprocess.TimeoutExpired:
        return _err("TIMEOUT", "Obfuscation timed out after 30s.", stage="runtime", http=408)
    except Exception as e:
        return _err("SERVER_ERROR", str(e), stage="server", http=500)
    finally:
        for p in (src_path, out_path):
            try: os.remove(p)
            except: pass

def _stats(original, obfuscated):
    return {
        "originalBytes":   len(original.encode("utf-8")),
        "obfuscatedBytes": len(obfuscated.encode("utf-8")),
        "originalLines":   original.count("\n") + 1,
        "obfuscatedLines": obfuscated.count("\n") + 1,
        "ratio":           round(len(obfuscated) / max(len(original), 1), 2),
    }

if __name__ == "__main__":
    port  = int(os.environ.get("PORT", 5000))
    debug = os.environ.get("DEBUG", "0") == "1"
    print(f"[Leviathan v3.3] http://0.0.0.0:{port}")
    app.run(host="0.0.0.0", port=port, debug=debug)
