"""
Levititas v3.3 — Web Server
server.py

Changes from v3.2:
  - Brand name generator integrated (randomized output headers)
  - /api/status returns region + node info
  - All v3.2 obfuscation APIs fully preserved
  - No Python fallback (Lua required)
  - Background effect state endpoint
"""

from flask import Flask, request, jsonify, render_template, send_from_directory
import subprocess, os, uuid, time, json, threading, shutil, random

# Import brand generator
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'static'))
try:
    from brand import generate_header_comment, generate_brand
except ImportError:
    def generate_brand(seed=None): return "Lev1titas"
    def generate_header_comment(seed=None):
        return f"-- This file was generated by {generate_brand(seed)} | {time.strftime('%Y-%m-%d')}"

app = Flask(__name__, template_folder="templates", static_folder="static")
app.config["MAX_CONTENT_LENGTH"] = 4 * 1024 * 1024

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "output")
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ── Cleanup ────────────────────────────────────────────────────
def _cleanup():
    while True:
        time.sleep(600)
        now = time.time()
        for f in os.listdir(OUTPUT_DIR):
            fp = os.path.join(OUTPUT_DIR, f)
            try:
                if now - os.path.getmtime(fp) > 600:
                    os.remove(fp)
            except Exception:
                pass
threading.Thread(target=_cleanup, daemon=True).start()

# ── Lua detection ──────────────────────────────────────────────
def _lua():
    for name in ("lua", "lua5.4", "lua54"):
        path = shutil.which(name)
        if path:
            return path
    return None

def _lua_version():
    lua = _lua()
    if not lua:
        return None
    try:
        r = subprocess.run([lua, "-v"], capture_output=True, text=True, timeout=5)
        return (r.stdout or r.stderr or "").strip()
    except Exception:
        return None

_LUA_PATH    = _lua()
_LUA_VERSION = _lua_version()
_CLI_PATH    = os.path.join(os.path.dirname(__file__), "levititas.lua")
_START_TIME  = time.time()

print(f"[Levititas v3.3] Starting")
if _LUA_PATH:
    print(f"[Levititas v3.3] ✓ Lua: {_LUA_VERSION}")
else:
    print("[Levititas v3.3] ✗ Lua not found — install Lua 5.4")

# ── Routes ─────────────────────────────────────────────────────
@app.route("/")
def index():
    return render_template("index.html")

@app.route("/api/status")
def status():
    uptime = int(time.time() - _START_TIME)
    return jsonify(
        version     = "3.3.0",
        lua         = bool(_LUA_PATH),
        lua_path    = _LUA_PATH,
        lua_version = _LUA_VERSION,
        engine      = "lua-full" if _LUA_PATH else "unavailable",
        ready       = bool(_LUA_PATH),
        uptime      = uptime,
        region      = os.environ.get("REGION", "global"),
        node        = os.environ.get("NODE",   "default"),
    )

@app.route("/api/compat")
def compat():
    return jsonify(matrix=[
        {"target":"lua54",  "status":"full",    "vm":"full",         "notes":"All features. Recommended."},
        {"target":"lua53",  "status":"partial", "vm":"full",         "notes":"No <const>/<close>."},
        {"target":"lua52",  "status":"none",    "vm":"none",         "notes":"Hard error."},
        {"target":"lua51",  "status":"none",    "vm":"none",         "notes":"Hard error."},
        {"target":"luajit", "status":"partial", "vm":"source-level", "notes":"No bitwise syntax."},
        {"target":"luau",   "status":"partial", "vm":"source-level", "notes":"No load() in Roblox."},
    ])

@app.route("/api/brand")
def brand():
    """Return a fresh randomized brand name."""
    seed = request.args.get("seed")
    build_seed = int(seed) if seed else None
    return jsonify(
        brand  = generate_brand(build_seed),
        header = generate_header_comment(build_seed),
    )

@app.route("/api/obfuscate", methods=["POST"])
def obfuscate():
    if not _LUA_PATH:
        return jsonify(
            ok    = False,
            error = (
                "Lua 5.4 is not installed on this server. "
                "Deploy using the provided Dockerfile which pre-installs Lua 5.4, "
                "or install Lua locally: https://www.lua.org/download.html"
            ),
            stage = "engine_check",
            code  = "NO_LUA_ENGINE",
        ), 503

    data   = request.get_json(force=True, silent=True) or {}
    source = data.get("source", "").strip()
    if not source:
        return jsonify(ok=False, error="No source code provided.", stage="input"), 400
    if len(source) > 800_000:
        return jsonify(ok=False, error="Source too large (max 800 KB).", stage="input"), 413

    opts   = data.get("options", {})
    target = opts.get("target", "lua54")
    seed   = opts.get("seed")
    maxIC  = opts.get("maxInstructions", 10_000_000)
    protect= opts.get("protectNames", [])

    valid_targets    = {"lua54","lua53","luajit","luau"}
    unsupported      = {"lua51","lua52"}
    if target in unsupported:
        return jsonify(ok=False, error=f"Target '{target}' is not supported. Supported: {', '.join(sorted(valid_targets))}", stage="compat", code="UNSUPPORTED_TARGET"), 400
    if target not in valid_targets:
        return jsonify(ok=False, error=f"Unknown target '{target}'.", stage="compat", code="UNKNOWN_TARGET"), 400

    uid      = uuid.uuid4().hex
    src_path = os.path.join(OUTPUT_DIR, f"{uid}_in.lua")
    out_path = os.path.join(OUTPUT_DIR, f"{uid}_out.lua")

    # Generate build seed for brand name
    build_seed = seed if seed else int(time.time() * 1000) ^ random.randint(0, 0xFFFF)
    brand_header = generate_header_comment(build_seed)

    try:
        with open(src_path, "w", encoding="utf-8") as f:
            f.write(source)

        args = [_LUA_PATH, _CLI_PATH, src_path, "-o", out_path,
                "--target", target, "--max-instr", str(int(maxIC))]

        if seed is not None:
            args += ["--seed", str(int(seed))]
        for name in protect:
            if name and name.strip():
                args += ["--protect", name.strip()]

        t0     = time.time()
        result = subprocess.run(args, capture_output=True, text=True, timeout=30)
        elapsed= round(time.time() - t0, 3)

        if result.returncode != 0:
            stderr = result.stderr or result.stdout or "Unknown error"
            return jsonify(ok=False, error=stderr.strip(), stage=_extract_stage(stderr), elapsed=elapsed), 422

        if not os.path.exists(out_path):
            return jsonify(ok=False, error="Obfuscator produced no output.", stage="output"), 500

        with open(out_path, "r", encoding="utf-8") as f:
            raw = f.read()

        # Replace any plain Levititas header with randomized brand header
        import re
        obfuscated = re.sub(
            r'^-- Levititas v[\d.]+ \|[^\n]*\n',
            brand_header + "\n",
            raw, count=1, flags=re.MULTILINE
        )
        if obfuscated == raw:
            # No header found — prepend one
            obfuscated = brand_header + "\n" + raw

        return jsonify(
            ok       = True,
            result   = obfuscated,
            elapsed  = elapsed,
            seed     = build_seed,
            brand    = brand_header,
            stats    = _stats(source, obfuscated),
            engine   = "lua-full",
        )

    except subprocess.TimeoutExpired:
        return jsonify(ok=False, error="Obfuscation timed out (30s).", stage="runtime", code="TIMEOUT"), 408
    except Exception as e:
        return jsonify(ok=False, error=str(e), stage="server"), 500
    finally:
        for p in (src_path, out_path):
            try: os.remove(p)
            except: pass

def _stats(original, obfuscated):
    return {
        "originalBytes":   len(original.encode()),
        "obfuscatedBytes": len(obfuscated.encode()),
        "originalLines":   original.count("\n") + 1,
        "obfuscatedLines": obfuscated.count("\n") + 1,
        "ratio":           round(len(obfuscated) / max(len(original), 1), 2),
    }

def _extract_stage(stderr):
    import re
    m = re.search(r'\[([A-Z]\d+)\]', stderr)
    if m:
        stages = {'P':'parse','V':'validation','B':'bytecode','R':'runtime','C':'compiler'}
        return stages.get(m.group(1)[0], 'unknown')
    return 'unknown'

if __name__ == "__main__":
    port  = int(os.environ.get("PORT", 5000))
    debug = os.environ.get("DEBUG", "0") == "1"
    print(f"[Levititas v3.3] http://0.0.0.0:{port}")
    app.run(host="0.0.0.0", port=port, debug=debug)
